import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header/>
        {children}
        </Providers>
      </body>
    </html>
  )
}

import {ConnectKitButton} from '@/components/wrappers/ConnectKitBtn'

function Header() {

  return <header className="flex flex-row items-center justify-end">
    <ConnectKitButton/>
  </header>
}